version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
      - backup:/backup
volumes:
  db_data:
  backup:
